@host=http://localhost:7071
@prefix=api


###
# local GetProductのGETリクエスト
POST {{host}}/api/CreateProduct

{
    "productId": "75542e38-563f-436f-adeb-f426f1dabb5c",
    "productName": "Starfruit Explosion",
    "productDescription": "This starfruit ice cream is out of this world!"
}

###
# AzureのAPIを叩く
POST https://serverless-httptrigger.azurewebsites.net/api/CreateProduct?code=naMGJyU21l8nFIJQ2ULuzH8C2U5am2vzzjzVZIfeX10zL2eG3ahqeg==

# 任意の値に変更。
{
    "productId": "75542e38-563f-436f-adeb-f426f1dabb5c",
    "productName": "Starfruit Explosion",
    "productDescription": "This starfruit ice cream is out of this world!"
}