@host=http://localhost:7071
@prefix=api


###
# local GetProductのGETリクエスト
@productId=test
GET {{host}}/api/GetProduct?productId={{productId}}

{
}


###
# Azure
@productIdAzure=tes2
GET https://serverless-httptrigger.azurewebsites.net/api/GetProduct?code=EFHqnklAvxFMGmjHzF4tCGfZzP0vJrxKniZPHPmsCuBFso96q9ZGKQ==&productId={{productIdAzure}}